air_wrist:
    joint_state_controller:
      type: joint_state_controller/JointStateController
      publish_rate: 50

    air_wrist_controller:
      type: effort_controllers/JointTrajectoryController
      joints:
        - roll_j
        - pitch_j
        - yaw_j
      gains:
        roll_j: {p: 20, i: 104.1667, d: 5.2083, i_clamp: 1.0}
        pitch_j: {p: 25, i: 104.1667, d: 5.2083, i_clamp: 1.0}
        yaw_j: {p: 25, i: 25.9701, d: 0.11985, i_clamp: 1.0}

      velocity_ff:
        roll_j: 2.23
        pitch_j: 2.23
        yaw_j: 0.149

      constraints:
        goal_time: 100.0                  # Override default

      state_publish_rate:  50            # Override default
      action_monitor_rate: 30            # Override default
      stop_trajectory_duration: 0        # Override default
