controller_list:
  - name: air_wrist/air_wrist_controller
    action_ns: follow_joint_trajectory
    type: FollowJointTrajectory
    default: true
    joints:
      - roll_j
      - pitch_j
      - yaw_j
